export const SEARCH_SPECIALITIES = 'SEARCH_SPECIALITIES';
export const SELECT_SPECIALITIES = 'SELECT_SPECIALITIES';
export const RESET_SPECIALITIES = 'RESET_SPECIALITIES';
export const OTHER_PAYMENT = 'OTHER_PAYMENT';

export const SEARCH_INSURANCES = 'SEARCH_INSURANCES';
export const SELECT_INSURANCES = 'SELECT_INSURANCES';
export const RESET_INSURANCES = 'RESET_INSURANCES';
